### ISSUE TITLE
What does 'sitepack' command do?

### ISSUE THREAD

**Issue by Dylanb-dev** [jamesknelson/sitepack#2]
I am trying to run this, initially had errors with node and babel so installed babel-cli as a dev dependency, now am being challenged by 

`/bin/sh: sitepack: command not found`

What can I do to fix this error?

**Comment by jamesknelson** [comment]
What context does that error appear in? Is it after following the "trying it out" instructions and running "yarn build"?

**Comment by Dylanb-dev** [comment]
Originally while running `yarn build` I had this error

```
dylan$ yarn build
yarn run v1.2.1
$ lerna run --parallel build
lerna info version 2.4.0
lerna info run in 2 package(s): npm run build
sitepack-react: > sitepack-react@1.0.0-beta.24 build /Users/dylan/Documents/dev/sitepack/packages/sitepack-react
sitepack-react: > npm run build:es && npm run build:commonjs
sitepack: > sitepack@1.0.0-beta.24 build /Users/dylan/Documents/dev/sitepack/packages/sitepack
sitepack: > cross-env BABEL_ENV=commonjs babel src --out-dir lib
sitepack: events.js:182\n      throw er; // Unhandled 'error' event\n      ^
sitepack: Error: spawn babel ENOENT\n    at _errnoException (util.js:1019:11)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)\n    at onErrorNT (internal/child_process.js:374:16)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)\n    at Function.Module.runMain (module.js:667:11)\n    at startup (bootstrap_node.js:187:16)\n    at bootstrap_node.js:607:3
```

Which stopped showing after I ran `npm install --save-dev babel-cli`.

However I realise this was a mistake and after running `yarn add babel-cli -D` the build still succeeds and I am able to run yarn start without getting the sitepack error.
